<a href="https://colab.research.google.com/github/YoungsunChoi914/class2022Fall/blob/main/regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Loading a dataset

In [1]:
import pandas as pd

### computer hardware dataset

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
computer_hardware = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/cpu-performance/machine.data', header=None, names=['vendor', 'model', 'MYCT', 'MMIN', 'MMAX', 'CACH', 'CHMIN', 'CHMAX', 'PRP', 'label'])
computer_hardware

vendor          model  MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  PRP  label
0    adviser          32/60   125   256   6000   256     16    128  198    199
1     amdahl         470v/7    29  8000  32000    32      8     32  269    253
2     amdahl        470v/7a    29  8000  32000    32      8     32  220    253
3     amdahl        470v/7b    29  8000  32000    32      8     32  172    253
4     amdahl        470v/7c    29  8000  16000    32      8     16  132    132
..       ...            ...   ...   ...    ...   ...    ...    ...  ...    ...
204   sperry           80/8   124  1000   8000     0      1      8   42     37
205   sperry  90/80-model-3    98  1000   8000    32      2      8   46     50
206   sratus             32   125  2000   8000     0      2     14   52     41
207     wang         vs-100   480   512   8000    32      0      0   67     47
208     wang          vs-90   480  1000   4000     0      0      0   45     25

[209 rows x 10 columns]

위에 두줄은 필요한함수를 가져온것. 
pandas에서 제공하는 read.csv 함수를 이용해서 이 url에 들어있는 데이터를 가지고 옴. 

header가 없어서, hearder 명을 여기서 적어줌. 

pandas엥서 가져왔으니까 dataframe 형태

le.fit_transform 함수 쓰면, vendor과 모델이 숫자가 아닌데, 저 함수를 쓰면 숫자로 나타내줌. 

In [3]:
computer_hardware['vendor'] = le.fit_transform(computer_hardware['vendor'])
computer_hardware['model'] = le.fit_transform(computer_hardware['model'])
computer_hardware.head()

vendor  model  MYCT  MMIN   MMAX  CACH  CHMIN  CHMAX  PRP  label
0       0     29   125   256   6000   256     16    128  198    199
1       1     62    29  8000  32000    32      8     32  269    253
2       1     63    29  8000  32000    32      8     32  220    253
3       1     64    29  8000  32000    32      8     32  172    253
4       1     65    29  8000  16000    32      8     16  132    132

9개의 입력값이 들어가서, label이 출력으로 나오게 될 것. 

출력은 진정한 의미의 숫자가 돼야 함. 그게 regression

### parkinsons dataset

In [4]:
parkinsons = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/telemonitoring/parkinsons_updrs.data')
parkinsons.head()

subject#  age  sex  test_time  motor_UPDRS  total_UPDRS  Jitter(%)  \
0         1   72    0     5.6431       28.199       34.398    0.00662   
1         1   72    0    12.6660       28.447       34.894    0.00300   
2         1   72    0    19.6810       28.695       35.389    0.00481   
3         1   72    0    25.6470       28.905       35.810    0.00528   
4         1   72    0    33.6420       29.187       36.375    0.00335   

   Jitter(Abs)  Jitter:RAP  Jitter:PPQ5  ...  Shimmer(dB)  Shimmer:APQ3  \
0     0.000034     0.00401      0.00317  ...        0.230       0.01438   
1     0.000017     0.00132      0.00150  ...        0.179       0.00994   
2     0.000025     0.00205      0.00208  ...        0.181       0.00734   
3     0.000027     0.00191      0.00264  ...        0.327       0.01106   
4     0.000020     0.00093      0.00130  ...        0.176       0.00679   

   Shimmer:APQ5  Shimmer:APQ11  Shimmer:DDA       NHR     HNR     RPDE  \
0       0.01309        0.01662      0.04314  0.014290  21.640  0.41888   
1       0.01072        0.01689      0.02982  0.011112  27.183  0.43493   
2       0.00844        0.01458      0.02202  0.020220  23.047  0.46222   
3       0.01265        0.01963      0.03317  0.027837  24.445  0.48730   
4       0.00929        0.01819      0.02036  0.011625  26.126  0.47188   

       DFA      PPE  
0  0.54842  0.16006  
1  0.56477  0.10810  
2  0.54405  0.21014  
3  0.57794  0.33277  
4  0.56122  0.19361  

[5 rows x 22 columns]

header정보가 들어있기때문에 여기서 따로 안넣어준것. 

통일을 위해 이름을 label로 바꿔줌

In [5]:
parkinsons.rename(columns={'motor_UPDRS':'label'}, inplace=True)
parkinsons.head()

subject#  age  sex  test_time   label  total_UPDRS  Jitter(%)  Jitter(Abs)  \
0         1   72    0     5.6431  28.199       34.398    0.00662     0.000034   
1         1   72    0    12.6660  28.447       34.894    0.00300     0.000017   
2         1   72    0    19.6810  28.695       35.389    0.00481     0.000025   
3         1   72    0    25.6470  28.905       35.810    0.00528     0.000027   
4         1   72    0    33.6420  29.187       36.375    0.00335     0.000020   

   Jitter:RAP  Jitter:PPQ5  ...  Shimmer(dB)  Shimmer:APQ3  Shimmer:APQ5  \
0     0.00401      0.00317  ...        0.230       0.01438       0.01309   
1     0.00132      0.00150  ...        0.179       0.00994       0.01072   
2     0.00205      0.00208  ...        0.181       0.00734       0.00844   
3     0.00191      0.00264  ...        0.327       0.01106       0.01265   
4     0.00093      0.00130  ...        0.176       0.00679       0.00929   

   Shimmer:APQ11  Shimmer:DDA       NHR     HNR     RPDE      DFA      PPE  
0        0.01662      0.04314  0.014290  21.640  0.41888  0.54842  0.16006  
1        0.01689      0.02982  0.011112  27.183  0.43493  0.56477  0.10810  
2        0.01458      0.02202  0.020220  23.047  0.46222  0.54405  0.21014  
3        0.01963      0.03317  0.027837  24.445  0.48730  0.57794  0.33277  
4        0.01819      0.02036  0.011625  26.126  0.47188  0.56122  0.19361  

[5 rows x 22 columns]

## Comparing Models

모델 왜 만듣나? prediction 할려고 

classification, regression 둘다 예측 목표

어떤게 더 정확히 예측하는지 어떻게 아나?

In [7]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.svm import LinearSVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.neural_network import MLPRegressor

models = [
    ('LR', LinearRegression()),
    ('L', Lasso()),
    ('R', Ridge()),
    ('SVR', LinearSVR()),
    ('DT', DecisionTreeRegressor()),
    ('NN', MLPRegressor()),
]

위에는 리니어리그래션, 젤 밑에는 뉴럴렛? (딥러닝)

데이터를 갖고 모델을 만드는데, 한 80%만 사용하고, 20%는 평가를 하는데 사용

### test a single model (e.g. Linear Regression)

In [11]:
from sklearn.model_selection import train_test_split
import numpy as np

dataset_name = 'computer_hardware'
dataset = computer_hardware

X = np.array(dataset.drop(['label'], axis=1))
y = np.array(dataset['label'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

name ='LR'
model = LinearRegression()
model.fit(X_train, y_train)
accuracy = model.score(X_test, y_test)
print(dataset_name, name, accuracy)

computer_hardware LR 0.9438611618299354


In [9]:
X

array([[  0,  29, 125, ...,  16, 128, 198],
       [  1,  62,  29, ...,   8,  32, 269],
       [  1,  63,  29, ...,   8,  32, 220],
       ...,
       [ 28,  28, 125, ...,   2,  14,  52],
       [ 29, 207, 480, ...,   0,   0,  67],
       [ 29, 208, 480, ...,   0,   0,  45]])

In [10]:
y

array([ 199,  253,  253,  253,  132,  290,  381,  381,  749, 1238,   23,
         24,   70,  117,   15,   64,   23,   29,   22,  124,   35,   39,
         40,   45,   28,   21,   28,   22,   28,   27,  102,  102,   74,
         74,  138,  136,   23,   29,   44,   30,   41,   74,   74,   74,
         54,   41,   18,   28,   36,   38,   34,   19,   72,   36,   30,
         56,   42,   34,   34,   34,   34,   34,   19,   75,  113,  157,
         18,   20,   28,   33,   47,   54,   20,   23,   25,   52,   27,
         50,   18,   53,   23,   30,   73,   20,   25,   28,   29,   32,
        175,   57,  181,  181,   32,   82,  171,  361,  350,  220,  113,
         15,   21,   35,   18,   20,   20,   28,   45,   18,   17,   26,
         28,   28,   31,   31,   42,   76,   76,   26,   59,   65,  101,
        116,   18,   20,   20,   30,   44,   44,   82,   82,  128,   37,
         46,   46,   80,   88,   88,   33,   46,   29,   53,   53,   41,
         86,   95,  107,  117,  119,  120,   48,  1

위에서 만든 거 dataset으로 두기

x: dataset이 엑셀타입의 dataframe으로 돼있는데, label칼럼의 값을 다 제외시켜서 array로 바꿔진 것

y: label 칼럼

ai머신러닝에서는 numpy로 다 바꿔줘야함. 

test와 train으로 나눠줌. test에 20퍼센트 하는 것. 그래서 변수가 4개가 설정. 훈련용/ 테스트용

함수를 그냥 모델로 불러온것. 그대로 써도 됨. 데이터에 맞게 훈련하는게 fit이라 함. ax+b에서 a랑 b를 구해주는 것. 

model.score가 테스트해주는 과정

94프로 확률로 정확히 계산해줌을 알 수 있다

In [12]:
model.predict(np.array([22, 122, 40, 8000, 16000, 32, 8, 16, 214]).reshape(1,9))

array([181.53279469])

만든 모델로 예측하기

입력값이 9개. 9개 숫자 아무거나 만들어서(리스트로) 리스트도 머신러닝에서는 안받아들이니까 array로 바꿔줌. 마지막 reshape가 중요함. 이거없으면 작동오류. 왜 들어가야 되나?

한꺼번에 많은 양 넣을때(batch), 2d로 받으면 편함. reshape에서 두칸이니까 2d array임)

reshape안할거면 애초에 숫자 쓸때 대괄호 2개 써서 표현해줘도 됨. 

### Evaluate all the models

In [13]:
for dataset_name, dataset in [('computer_hardware', computer_hardware), ('parkinsons', parkinsons)]:
    X = np.array(dataset.drop(['label'], axis=1))
    y = np.array(dataset['label'])
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    for name, model in models:
        model.fit(X_train, y_train)
        accuracy = model.score(X_test, y_test)
        print(dataset_name, name, accuracy)

computer_hardware LR 0.9438611618299354
computer_hardware L 0.9439215152431056
computer_hardware R 0.9438612466623207
computer_hardware SVR 0.7841072825246005
computer_hardware DT 0.8747998202542484
computer_hardware NN -12.594627059760562
parkinsons LR 0.9068547520909843
parkinsons L 0.8983382060322662
parkinsons R 0.9049789120180208


/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/svm/_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


parkinsons SVR 0.8265541556508434
parkinsons DT 0.9987206718569621
parkinsons NN 0.965953996661194


/usr/local/lib/python3.8/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


outer loop에는 데이타셋이 2개, inner loop에는 모델 6개가 있다. 

6X2 해서 12개의 값이 나옴. 